export const FETCH_VIDEOGAMES = "FETCH VIDEOGAMES";
export const SEARCH_VIDEOGAMES = "SEARCH VIDEOGAMES"
export const SORT = "SORT"
export const FETCH_GENRES="FETCH GENRES"
export const FILTERBYGENRE = "FILTER BY GENRE"
export const VIDEOGAMEORIGIN = "VIDEOGAME ORIGIN"